# Generated by Django 3.1.1 on 2020-10-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backuprun",
            name="ended",
            field=models.DateTimeField(blank=True, null=True, verbose_name="ended"),
        ),
    ]
